
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "0063"
  socket: /tmp/mysql.sock
  host: localhost

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test
